### ISSUE TITLE
Unable to parse option value "gbr"

### ISSUE THREAD

**Issue by vanastasis** [lisamelton/other_video_transcoding#206] opened 2024-07-13 15:49 UTC
Hi

ffmpeg -loglevel error -stats -i input.mk -map 0:0 -c:v hevc_nvenc -pix_fmt:v p010le -b:v 5000k -maxrate:v 12000k -bufsize:v 12000k -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v gbr -metadata:s:v title\= -disposition:v default -map 0:1 -c:a:0 copy -metadata:s:a:0 title\= -disposition:a:0 default -map 0:2 -c:s:0 copy -disposition:s:0 0 -metadata:g title\= -default_mode passthrough output.mkv

some files have extra meta data in it which see extra colorspace information which puts in -colorspace:v gbr 
to which i only want to set bt709 

[hevc_nvenc @ 0x625b4c1f23c0] [Eval @ 0x7ffd58881b20] Undefined constant or missing '(' in 'gbr'
[hevc_nvenc @ 0x625b4c1f23c0] Unable to parse option value "gbr"
[hevc_nvenc @ 0x625b4c1f23c0] Error setting option colorspace to value gbr.
[vost#0:0/hevc_nvenc @ 0x625b4c228040] Error applying encoder options: Invalid argument

on few files getting this error.

any help please, thank you

**Comment by lisamelton** [comment] 2024-07-13 16:13
@vanastasis I'm sorry you're having this problem. I need to no more about your input files to diagnose what's going on. Can you attach dumps from MediaInfo or `.log` files produced using the `--debug` option on at least one of these files?

**Comment by vanastasis** [comment] 2024-07-13 17:32
Hi

[Not Working.txt](https://github.com/user-attachments/files/16203067/Not.Working.txt)
[Working.txt](https://github.com/user-attachments/files/16203068/Working.txt)

on the not working.txt lines 166 - 173 is the only thing i see different which could prevent encoding.

else the working file encodes without any issues.

**Comment by lisamelton** [comment] 2024-07-13 18:24
@vanastasis Thanks for the MediaInfo dumps! And, I agree, that's where the issue is. Apparently, your video stream is using the `gbr` colorspace and I'm just copying that from the media scan by `ffprobe` and copying it as an argument to `ffmpeg` for the `-colorspace` option.

I just checked the FFmpeg documentation and `gbr` is a valid value for that option. At least with the latest version of `ffmpeg`. Which version of `ffmpeg` are you running?

**Comment by vanastasis** [comment] 2024-07-13 18:27
Hi

ffmpeg version N-116211-g9fb8d13d56-20240709

**Comment by lisamelton** [comment] 2024-07-14 03:14
@vanastasis OK, that's definitely not an official release version. Can you try with version 7.0.1?

**Comment by vanastasis** [comment] 2024-07-14 07:50
Hi

Debian Bookworm version 5.1.5-0+deb12u1 fails - latest in repository
compiled from ffmpeg github source and same issue
https://github.com/BtbN/FFmpeg-Builds is the build i use which implements everything 
 
same issue

I have found a way around it but its like the LONG way but it works (re-encoding and removing all metadata then i can use the script)

**Comment by lisamelton** [comment] 2024-07-14 15:19
@vanastasis OK, clearly there is a bug in `ffmpeg` then. Ouch! It's not taking the same `-colorspace` value returned by `ffprobe`. And `other-transcode.rb` is just passing through that value.

Soooo... I'm not sure what to do about this. I could detect `gbr` and simply replace it with `bt709`. But that's likely to cause other problems.

Where did you get these source videos? They're not Blu-ray rips, right?

**Comment by vanastasis** [comment] 2024-07-14 15:38
Hi

Files were supplied to me in that format
Unknown how they were made and from what media. 

What do you suggest ?

If it's with ffmpeg submitting a bug report. 

I believe you have more expertise in this matter than I.

If you were to edit your code would that not affect HDR bt2020 ?

**Comment by lisamelton** [comment] 2024-07-14 18:05
@vanastasis Apparently `gbr` is the 8-bit planar, as opposed to 8-bit packed, version of `rgb` Sooooo... Maybe just ignoring `gbr` on input and letting `other-transcode.rb` set it to one of its depth-specific defaults would work? Which would be `bt2020nc` or `bt709`.

Let me make that change later today and then you can try it. I'll comment here when it's checked it...

**Comment by lisamelton** [comment] 2024-07-14 18:21
@vanastasis OK, the change to ignore `gbr` has been checked in and pushed. Please download `other-transcode.rb`, try it out, and let me know if that fixes your problem.

**Comment by vanastasis** [comment] 2024-07-15 01:09
Hi,

tested with a few files which I had issues with and they all converted without issues. everything seems good.
found another issue, log files are no longer being created, only converting file (log output is helpful in situations like this) 

[converting.txt](https://github.com/user-attachments/files/16229299/converting.txt)

Thank you or your work :)

**Comment by lisamelton** [comment] 2024-07-15 02:54
@vanastasis I'm glad that fixed your problem! And you are very welcome.

I intentionally disabled `.log` file creation by default last week. But using the `--debug` option will create one. I mentioned all this in the "CHANGELOG.md" file.

Anyway, I'll close this now since the issue is resolved.

**Closed by lisamelton** 2024-07-15 02:54 UTC
Labels: bug
